### 머신러닝(다중분류 문제) - 은행정보로 신용등급을 예측하시오.

In [10]:
import pandas as pd 

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_train.csv") 
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_test.csv")

In [ ]:
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("\n")

print("===== 데이터 정보(자료형) =====")
print(train.info())
print("\n")

print("===== train 결측치 수 =====")
print(train.isnull().sum().sum())
print("\n")

print("===== test 결측치 수 =====")
print(test.isnull().sum().sum())
print("\n")

print("===== target 빈도 =====")
print(train['Credit_Score'].value_counts())

===== 데이터 크기 =====
Train Shape: (4198, 21)
Test Shape: (1499, 20)


===== 데이터 정보(자료형) =====
<class 'pandas.DataFrame'>
RangeIndex: 4198 entries, 0 to 4197
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       4198 non-null   float64
 1   Num_of_Delayed_Payment    4198 non-null   float64
 2   Num_Credit_Inquiries      4198 non-null   float64
 3   Credit_Utilization_Ratio  4198 non-null   float64
 4   Credit_History_Age        4198 non-null   float64
 5   Payment_of_Min_Amount     4198 non-null   str
 6   Amount_invested_monthly   4198 non-null   float64
 7   Monthly_Balance           4198 non-null   float64
 8   Credit_Mix                4198 non-null   str
 9   Payment_Behaviour         4198 non-null   str
 10  Age                       4198 non-null   float64
 11  Annual_Income             4198 non-null   float64
 12  Num_Bank_Accounts         4198 non-null   float64
 13  Num_Credit_Card           4198 non-null   float64
 14  Interest_Rate             4198 non-null   float64
 15  Num_of_Loan               4198 non-null   float64
 16  Monthly_Inhand_Salary     4198 non-null   float64
 17  Changed_Credit_Limit      4198 non-null   float64
 18  Outstanding_Debt          4198 non-null   float64
 19  Total_EMI_per_month       4198 non-null   float64
 20  Credit_Score              4198 non-null   str
dtypes: float64(17), str(4)
memory usage: 688.9 KB
None


===== train 결측치 수 =====
0


===== test 결측치 수 =====
0


===== target 빈도 =====
Credit_Score
Standard    2225
Poor        1232
Good         741
Name: count, dtype: int64

In [12]:
target = train.pop('Credit_Score')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

In [ ]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

print("\n ===== 분할된 데이터 크기 =====")
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

 ===== 분할된 데이터 크기 =====
(3358, 29) (840, 29) (3358,) (840,)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

 f1-macro: 0.7004593488873695

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

 f1-macro: 0.7004593488873695

### 머신러닝(회귀분석 문제) - 차량의 특징 기반 데이터를 활용하여 중고차 가격을 예측하시오.

In [ ]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part4/ch5/test.csv")

In [17]:
train.shape, test.shape

((3759, 9), (1617, 8))

In [18]:
train.head(3)

       model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   EcoSport  2017  10298       Manual    25013   Petrol  150  53.3         1.0
1      Focus  2016  10491       Manual    30970   Diesel    0  74.3         1.5
2      S-MAX  2017  13498       Manual    60200   Diesel  150  56.5         2.0

In [19]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 3759 entries, 0 to 3758
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         3759 non-null   str
 1   year          3759 non-null   int64
 2   price         3759 non-null   int64
 3   transmission  3759 non-null   str
 4   mileage       3759 non-null   int64
 5   fuelType      3759 non-null   str
 6   tax           3759 non-null   int64
 7   mpg           3759 non-null   float64
 8   engineSize    3759 non-null   float64
dtypes: float64(2), int64(4), str(3)
memory usage: 264.4 KB

In [20]:
train.describe()

              year         price  ...          mpg   engineSize
count  3759.000000   3759.000000  ...  3759.000000  3759.000000
mean   2016.887736  12353.321362  ...    57.793083     1.352807
std       2.151811   4750.338051  ...    10.099221     0.437130
min    2002.000000   1095.000000  ...    20.900000     0.000000
25%    2016.000000   9000.000000  ...    52.300000     1.000000
50%    2017.000000  11495.000000  ...    58.900000     1.200000
75%    2018.000000  15310.000000  ...    65.700000     1.500000
max    2060.000000  48000.000000  ...   201.800000     5.000000

[8 rows x 6 columns]

In [22]:
train.describe(include='O')

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_32516\929496668.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  train.describe(include='O')

          model transmission fuelType
count      3759         3759     3759
unique       19            3        3
top      Fiesta       Manual   Petrol
freq       1372         3234     2541

In [23]:
train.isnull().sum().sum()

np.int64(0)

In [24]:
test.isnull().sum().sum()

np.int64(0)

In [25]:
target = train.pop('price')

print(train.shape, test.shape)
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.shape, test.shape)

(3759, 8) (1617, 8)
(3759, 30) (1617, 30)

In [29]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((3007, 30), (752, 30), (3007,), (752,))

In [31]:
from sklearn.metrics import root_mean_squared_error
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)
root_mean_squared_error(y_val, pred)

1341.943732584459

In [33]:
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)


print(pd.read_csv("result.csv").head())

       pred
0  15586.88
1  15407.71
2  14912.47
3  18482.73
4   6168.01